modLoader="javafml"
loaderVersion="[${loader_version},)"

[[mods]]
    modId="dungeons_etc"
    version="${version}"
    displayName="Dungeons Etc."
    logoFile="logo.png"
    credits="Swordofblaze, BlackbirdAntlion, Bombadil, Sarinsa, Sam, Some Blue Guy"
    authors="Swordofblaze"
    description="Dungeons, trinkets, monsters and more."



