modLoader="javafml"
loaderVersion="[34,)"
license="GPLv3"

[[mods]]
    modId="dungeons_etc"
    version="${file.jarVersion}"
    displayName="Dungeons Etc."
    logoFile="logo.png"
    credits="Swordofblaze, BlackbirdAntlion, Bombadil, Sarinsa, Sam, Some Blue Guy"
    authors="Swordofblaze"
    description="Dungeons, trinkets, monsters etc."

[[dependencies.dungeons_etc]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    side="BOTH"

[[dependencies.dungeons_etc]]
    modId="forge"
    mandatory=true
    versionRange="[35.1.7,)"
    side="BOTH"
